version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: questiondb_postgres
    environment:
      POSTGRES_DB: questiondb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data: